const HOST_API = "127.0.0.1";
const PORTA_API = 4317;
const INDIRIZZO_API = `http://${HOST_API}:${PORTA_API}`;
const LIMITE_RICHIESTA_BYTE = 44e5;
const LIMITE_PAGINA_BYTE = 4e6;
export {
  HOST_API,
  INDIRIZZO_API,
  LIMITE_PAGINA_BYTE,
  LIMITE_RICHIESTA_BYTE,
  PORTA_API
};
